import torch
import torch.nn as nn
from typing import Dict, Any
import numpy as np

class SDMoSETrainer:
    """
    Hybrid Discrete-Continuous Optimizer executing the SD-MoSE 
    3-level Variational EM algorithmic loop (Regime Discovery).
    """
    def __init__(self, agent: Any, gate_module: nn.Module, elbo_module: nn.Module, 
                 lr: float = 1e-3, entropy_min: float = 0.1, lambdas: Dict[str, float] = None):
        """
        Args:
            agent: The core SDMoSEAgent orchestrator handling PySR searches
            gate_module: Differentiable SymbolicGate network
            elbo_module: Variational JointELBO inference formulation
            lr: Adam learning rate for continuous outer-loop optimization
            entropy_min: H_min boundary for early collapse prevention
            lambdas: Dictionary of regularization weights
        """
        self.agent = agent
        self.gate = gate_module
        self.elbo = elbo_module
        
        # Level 2 Continuous Optimization (Alpha / Beta structural coefficients)
        self.optimizer = torch.optim.Adam(self.gate.parameters(), lr=lr)
        self.entropy_min = entropy_min
        
        # Default loss weights mapping the analytical composite
        self.lambdas = lambdas or {
            "gate": 0.01,
            "kl": 1.0,
            "stab": 1.0,
            "phys": 10.0,
            "complex": 0.01
        }
        
    def train_step(self, x: torch.Tensor, y: torch.Tensor, t: int) -> Dict[str, Any]:
        """
        Executes one full iteration of the Variational EM discovery loop.
        
        Args:
            x: Raw input covariates (Batch, Features)
            y: Target physical metric
            t: Iteration index t
        Returns:
            Dictionary tracking joint stability loss metrics.
        """
        self.optimizer.zero_grad()
        
        # --- INNER LOOP (M-Step): Symbolic Hypothesis Refinement ---
        # --- (A) PERCEPTION ---
        # Agent extracts physical baseline features
        x_numpy = x.detach().cpu().numpy()
        self.agent.observe({"x": x_numpy, "y": y.detach().cpu().numpy()})
        
        # --- (B) GATE (E-Step) ---
        # Forward pass through symbolic gate to get differentiable regime routing assignments (z_t)
        # pi_k(t) = SymbolicGate(x_t', phi_k, alpha_k)
        gate_probs = self.gate(x) # Shape: (Batch, Num_Regimes)
        
        # --- (C, D, E, F) RETRIEVE, GENERATE, VERIFY, SCORE ---
        # Level 1: Symbolic Search (Discrete string-space evaluation)
        self.agent.retrieve()
        self.agent.reason() # Execute PySR/gradient-free trees 
        verified_hypotheses = self.agent.verify() # Score against hard physical clique potentials
        
        # --- (G, H, I) UPDATE MEMORY & BELIEFS ---
        # The agent natively updates the regime tracking history via InformationGeometric trajectories
        self.agent.learn()
        
        # --- (Level 3) VARIATIONAL INFERENCE & FORMAL LOSS DECOMPOSITION ---
        batch_size = x.shape[0]
        num_regimes = self.gate.num_experts if hasattr(self.gate, 'num_experts') else gate_probs.shape[1]
        device = x.device
        
        # Initialize tracking tensors for detached empirical bounds
        L_recon_tensor = torch.zeros((batch_size, num_regimes), device=device)
        L_stab_tensor = torch.zeros((batch_size, num_regimes), device=device)
        L_phys_tensor = torch.zeros((batch_size, num_regimes), device=device)
        
        for h in verified_hypotheses:
            if hasattr(h, 'regime_id') and h.regime_id is not None:
                k = h.regime_id
                
                # Extract strict mathematical evaluations directly generated by discrete engine tracking
                mse_bounds = float(getattr(h, 'mse', 0.0))
                stab_bounds = float(getattr(h, 'stability_penalty', 0.0))
                phys_bounds = float(getattr(h, 'violations_penalty', 0.0))
                
                L_recon_tensor[:, k] += torch.tensor(mse_bounds, dtype=torch.float32, device=device)
                L_stab_tensor[:, k] += torch.tensor(stab_bounds, dtype=torch.float32, device=device)
                L_phys_tensor[:, k] += torch.tensor(phys_bounds, dtype=torch.float32, device=device)
        
        # 1. Expected L_recon = sum_k pi_k * MSE_k
        L_recon = torch.sum(gate_probs * L_recon_tensor)
        
        # 2. L_gate (L0 Sparsity via custom Straight-Through Estimator)
        L_gate = self.gate.sparsity_loss()
        
        # 3. Explicit tracking constraints
        L_stab = torch.sum(gate_probs * L_stab_tensor)
        L_phys = torch.sum(gate_probs * L_phys_tensor)
        
        # Retrieve the pure Temporal Markov sequences tracking the KL HMM metrics (L_KL)
        dummy_likelihoods = torch.zeros_like(L_recon_tensor)
        loss_components = self.elbo(log_likelihoods=dummy_likelihoods, gate_probs=gate_probs)
        L_KL = loss_components["kl_z"]
        
        # ---- COMPLETE LOSS FUNCTION ----
        total_loss = L_recon + \
                     self.lambdas["gate"] * L_gate + \
                     self.lambdas["kl"] * L_KL + \
                     self.lambdas["stab"] * L_stab + \
                     self.lambdas["phys"] * L_phys
        
        # (J) Penalize Collapse: Entropy Bonus
        # H[pi(t+1)] preventing premature modal starvation
        avg_gate = gate_probs.mean(dim=0)
        entropy = -torch.sum(avg_gate * torch.log(avg_gate + 1e-12))
        
        if entropy < self.entropy_min:
            # Entropy bonus pushing probability density back into uncharted sub-regimes
            total_loss -= 0.1 * entropy 
            
        # Update Continuous Parameters (Adam natively backpropagating through L0 bounds)
        total_loss.backward()
        self.optimizer.step()
        
        return {
            "loss": total_loss.item(),
            "recon": L_recon.item(),
            "gate": L_gate.item(),
            "kl_z": L_KL.item(),
            "stab": L_stab.item(),
            "phys": L_phys.item(),
            "entropy": entropy.item(),
            "gate_probs": gate_probs.detach().cpu().numpy()
        }
