name: sdmose
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - scikit-learn
  - xarray
  - dask
  - netcdf4
  - h5netcdf
  - matplotlib
  - sympy
  - pytorch
  - cpuonly # Remove if GPU is available
  - wandb
  - mlflow
  - hydra-core
  - dvc
  - pytest
  - black
  - mypy
  - jupyterlab
  - pip
  - pip:
    - pysr
    - gplearn
    - causal-learn
    - tigramite
    - shap
    - climax
    - fourcastnet
    - transformers
