from typing import Any

import torch
from torch import nn


class DiscoveryTrainer:
    """
    Hybrid discrete-continuous optimizer executing the equation-discovery
    agent's 3-level variational EM loop (regime discovery).
    """
    def __init__(self, agent: Any, gate_module: nn.Module, elbo_module: nn.Module,
                 lr: float = 1e-3, entropy_min: float = 0.1,
                 lambdas: dict[str, float] | None = None):
        """
        Args:
            agent: The core DiscoveryAgent orchestrator handling symbolic-regression searches
            gate_module: Differentiable SymbolicGate network
            elbo_module: Variational JointELBO inference formulation
            lr: Adam learning rate for continuous outer-loop optimization
            entropy_min: H_min boundary for early collapse prevention
            lambdas: Dictionary of regularization weights
        """
        self.agent = agent
        self.gate = gate_module
        self.elbo = elbo_module

        # Level 2 continuous optimization (alpha / beta structural coefficients)
        self.optimizer = torch.optim.Adam(self.gate.parameters(), lr=lr)
        self.entropy_min = entropy_min

        # Default loss weights mapping the analytical composite
        self.lambdas = lambdas or {
            "gate": 0.01,
            "kl": 1.0,
            "stab": 1.0,
            "phys": 10.0,
            "complex": 0.01
        }

    def train_step(self, x: torch.Tensor, y: torch.Tensor, t: int) -> dict[str, Any]:
        """
        Executes one full iteration of the variational EM discovery loop.

        Args:
            x: Raw input covariates (Batch, Features)
            y: Target values
            t: Iteration index t
        Returns:
            Dictionary tracking joint loss metrics.
        """
        self.optimizer.zero_grad()

        # --- INNER LOOP (M-Step): Symbolic Hypothesis Refinement ---
        # --- (A) PERCEPTION ---
        # Agent extracts baseline features
        x_numpy = x.detach().cpu().numpy()
        self.agent.observe({"x": x_numpy, "y": y.detach().cpu().numpy()})

        # --- (B) GATE (E-Step) ---
        # Forward pass through symbolic gate to get differentiable regime routing assignments (z_t)
        # pi_k(t) = SymbolicGate(x_t', phi_k, alpha_k)
        gate_probs = self.gate(x)  # Shape: (Batch, Num_Regimes)

        # --- (C, D, E, F) RETRIEVE, GENERATE, VERIFY, SCORE ---
        # Level 1: Symbolic search (discrete string-space evaluation)
        self.agent.retrieve()
        self.agent.reason()  # Execute symbolic-regression / gradient-free search
        verified_hypotheses = self.agent.verify()  # Score against hard validity checks

        # --- (G, H, I) UPDATE MEMORY & BELIEFS ---
        # The agent natively updates the regime tracking history via its confidence trajectory
        self.agent.learn()

        # --- (Level 3) VARIATIONAL INFERENCE & FORMAL LOSS DECOMPOSITION ---
        batch_size = x.shape[0]
        num_regimes = self.gate.num_experts if hasattr(self.gate, 'num_experts') else gate_probs.shape[1]
        device = x.device

        # Initialize tracking tensors for detached empirical bounds
        L_recon_tensor = torch.zeros((batch_size, num_regimes), device=device)
        L_stab_tensor = torch.zeros((batch_size, num_regimes), device=device)
        L_phys_tensor = torch.zeros((batch_size, num_regimes), device=device)

        for h in verified_hypotheses:
            if hasattr(h, 'regime_id') and h.regime_id is not None:
                k = h.regime_id

                # Extract strict mathematical evaluations directly generated by discrete engine tracking
                mse_bounds = float(getattr(h, 'mse', 0.0))
                stab_bounds = float(getattr(h, 'stability_penalty', 0.0))
                phys_bounds = float(getattr(h, 'violations_penalty', 0.0))

                L_recon_tensor[:, k] += torch.tensor(mse_bounds, dtype=torch.float32, device=device)
                L_stab_tensor[:, k] += torch.tensor(stab_bounds, dtype=torch.float32, device=device)
                L_phys_tensor[:, k] += torch.tensor(phys_bounds, dtype=torch.float32, device=device)

        # 1. Expected L_recon = sum_k pi_k * MSE_k
        L_recon = torch.sum(gate_probs * L_recon_tensor)

        # 2. L_gate (L0 sparsity via custom straight-through estimator)
        L_gate = self.gate.sparsity_loss()

        # 3. Explicit tracking constraints
        L_stab = torch.sum(gate_probs * L_stab_tensor)
        L_phys = torch.sum(gate_probs * L_phys_tensor)

        # Retrieve the pure temporal Markov sequences tracking the KL HMM metrics (L_KL)
        dummy_likelihoods = torch.zeros_like(L_recon_tensor)
        loss_components = self.elbo(log_likelihoods=dummy_likelihoods, gate_probs=gate_probs)
        L_KL = loss_components["kl_z"]
        elbo_value = loss_components.get("elbo")

        # ---- COMPLETE LOSS FUNCTION ----
        total_loss = L_recon + \
                     self.lambdas["gate"] * L_gate + \
                     self.lambdas["kl"] * L_KL + \
                     self.lambdas["stab"] * L_stab + \
                     self.lambdas["phys"] * L_phys

        # (J) Penalize collapse: entropy bonus
        # H[pi(t+1)] preventing premature modal starvation
        avg_gate = gate_probs.mean(dim=0)
        entropy = -torch.sum(avg_gate * torch.log(avg_gate + 1e-12))

        if entropy < self.entropy_min:
            # Entropy bonus pushing probability density back into uncharted sub-regimes
            total_loss -= 0.1 * entropy

        # Update continuous parameters (Adam natively backpropagating through L0 bounds)
        total_loss.backward()
        self.optimizer.step()

        return {
            "loss": total_loss.item(),
            "elbo": elbo_value.item() if elbo_value is not None else None,
            "recon": L_recon.item(),
            "gate": L_gate.item(),
            "kl_z": L_KL.item(),
            "stab": L_stab.item(),
            "phys": L_phys.item(),
            "entropy": entropy.item(),
            "gate_probs": gate_probs.detach().cpu().numpy()
        }
