"""Collate audit sweeps across budgets into one table.

    python scripts/summarize_audit.py

Reads every `budget_*/audit.json` under the results directory and writes
`summary.md` and `summary.csv` beside them. Nothing here recomputes a verdict --
it only arranges what the sweeps recorded, so the summary cannot disagree with
its sources.

RFC-0001 section 4.1 makes nullity indexed by budget: a wrapper may be null at
one budget and contribute at another, and a verdict reported without its budget
means nothing. This script exists to make that indexing visible rather than
leaving three separate files for a reader to reconcile.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

# Ordered smallest-first so the table reads as a budget curve rather than as an
# alphabetical accident.
BUDGET_ORDER = ["budget_small", "budget_medium", "budget_large"]

METRICS = ["rmse", "symbolic_complexity", "exact_recovery"]

EXPECTED_PROBLEMS = 8


def load_sweeps(root: Path) -> dict[str, dict[str, Any]]:
    """Every subdirectory holding an audit.json, known names ordered first.

    Discovered rather than enumerated. The original list hardcoded three budget
    directory names, so a sweep written anywhere else was silently absent from
    the summary -- a collation step that quietly omits results is worse than no
    collation step. Known names keep their deliberate smallest-first order;
    anything else follows alphabetically, so the output stays deterministic.
    """
    found = {path.parent.name: path for path in sorted(root.glob("*/audit.json"))}
    ordered = [name for name in BUDGET_ORDER if name in found]
    ordered += sorted(name for name in found if name not in BUDGET_ORDER)

    sweeps: dict[str, dict[str, Any]] = {}
    for name in ordered:
        sweeps[name] = json.loads(found[name].read_text(encoding="utf-8"))
    return sweeps


def to_rows(sweeps: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for budget, payload in sweeps.items():
        config = payload.get("config", {})
        for report in payload.get("reports", []):
            for metric, verdict in report.get("per_metric", {}).items():
                rows.append(
                    {
                        "budget": budget.replace("budget_", ""),
                        "domain": config.get("domain"),
                        "scaffold": config.get("scaffold"),
                        "evaluations_per_fit": config.get("evaluations_per_fit"),
                        "seeds": config.get("seeds"),
                        "equation_id": report["equation_id"],
                        "metric": metric,
                        "verdict": verdict["verdict"],
                        "observed_difference": verdict["observed_difference"],
                        "ci_low": verdict["ci_low"],
                        "ci_high": verdict["ci_high"],
                        "margin": verdict["margin"],
                        "power": verdict["power"],
                        "overall_verdict": report["verdict"],
                        "degenerate": report.get("degenerate"),
                        "identical_rate": report.get("identical_representation_rate"),
                    }
                )
    return rows


def _verdict_grid(rows: list[dict[str, Any]], metric: str) -> list[str]:
    """One markdown table: equations down, budgets across, for a single metric."""
    budgets = [b for b in ("small", "medium", "large") if any(r["budget"] == b for r in rows)]
    equations = sorted({r["equation_id"] for r in rows})

    lines = [f"### {metric}", ""]
    lines.append("| equation | " + " | ".join(budgets) + " |")
    lines.append("|---" * (len(budgets) + 1) + "|")
    for equation in equations:
        cells = []
        for budget in budgets:
            match = [
                r
                for r in rows
                if r["equation_id"] == equation and r["budget"] == budget and r["metric"] == metric
            ]
            if not match:
                cells.append("-")
                continue
            row = match[0]
            cells.append(f"{row['verdict']}<br>{row['observed_difference']:+.3g}")
        lines.append(f"| `{equation}` | " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def build_markdown(sweeps: dict[str, dict[str, Any]], rows: list[dict[str, Any]]) -> str:
    lines = [
        "# Null-scaffold audit: results across budgets",
        "",
        "Generated by `scripts/summarize_audit.py`. Do not edit by hand -- every",
        "number here is copied from a sweep's `audit.json`, and regenerating the",
        "sweeps regenerates this file.",
        "",
        "## Sweeps included",
        "",
        "| sweep | domain | evaluations per fit | seeds | problems completed |",
        "|---|---|---|---|---|",
    ]
    for name, payload in sweeps.items():
        config = payload.get("config", {})
        lines.append(
            f"| {name.replace('budget_', '')} | {config.get('domain', '-')} | "
            f"{config.get('evaluations_per_fit')} | "
            f"{config.get('seeds')} | {config.get('problems_completed')} |"
        )

    incomplete = [
        name
        for name, payload in sweeps.items()
        if payload.get("config", {}).get("problems_completed", 0) < EXPECTED_PROBLEMS
    ]
    if incomplete:
        lines += [
            "",
            (
                f"**Partial:** {', '.join(incomplete)} had not finished all "
                f"{EXPECTED_PROBLEMS} problems when this was generated. Stated here rather "
                "than left for a reader to infer from a short table."
            ),
        ]

    lines += ["", "## Verdicts", ""]
    for metric in METRICS:
        lines += _verdict_grid(rows, metric)

    # Degeneracy is a property of the wrapper, not of a metric, so it gets its
    # own table rather than a column repeated three times.
    lines += ["## Intra-run degeneracy", "", "| budget | equation | degenerate |", "|---|---|---|"]
    seen: set[tuple[str, str]] = set()
    for row in rows:
        key = (row["budget"], row["equation_id"])
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"| {row['budget']} | `{row['equation_id']}` | {row['degenerate']} |")

    lines += [
        "",
        "## Reading this",
        "",
        "`CONTRIBUTES` means the scaffold beat its own base searcher at matched",
        "compute. `HARMFUL` means it lost. `NULL` means equivalence was established",
        "within the pre-registered margin. `INCONCLUSIVE` means the design lacked the",
        "power to distinguish those -- it is not evidence of no effect.",
        "",
        "`power` in the CSV is power to conclude *equivalence*. It is near zero on any",
        "verdict that is not `NULL`, which is correct and not a warning sign.",
        "",
        "Per-metric verdicts are uncorrected for multiplicity; see each report's",
        "`limitations` field.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPO_ROOT / "results" / "null_scaffold_audit")
    args = parser.parse_args()

    sweeps = load_sweeps(args.root)
    if not sweeps:
        print(f"[summary] no sweeps found under {args.root}")
        return 1

    rows = to_rows(sweeps)
    (args.root / "summary.md").write_text(build_markdown(sweeps, rows), encoding="utf-8")
    if rows:
        with (args.root / "summary.csv").open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)

    print(f"[summary] {len(sweeps)} sweeps, {len(rows)} metric rows")
    print(f"[summary] wrote {args.root / 'summary.md'} and {args.root / 'summary.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
